<script setup>
import { computed, reactive, ref } from 'vue'
import TerminalPane from './TerminalPane.vue'
import { canPause, tabLabel } from '../lib/status.js'
import { sessionCapabilities } from '../lib/access.js'
const props = defineProps({ session: Object }); defineEmits(['back', 'resume', 'pause'])
const capabilities = computed(() => sessionCapabilities(props.session)); const isLive = computed(() => ['Running', 'Pending'].includes(props.session?.phase)); const activeTab = ref('agent'); const shellOpened = ref(false); const statuses = reactive({ agent: 'connecting…', shell: '' })
function selectTab(tab) { if (tab === 'shell') shellOpened.value = true; activeTab.value = tab }
</script>
<template><div class="term-wrap"><div class="term-bar"><button class="back" @click="$emit('back')">‹ Back</button><span class="title">{{ session.title }}</span><nav v-if="isLive && capabilities.canShell" class="tabs"><button :class="{ on: activeTab === 'agent' }" @click="selectTab('agent')">{{ tabLabel('agent') }}</button><button :class="{ on: activeTab === 'shell' }" @click="selectTab('shell')">{{ tabLabel('shell') }}</button></nav><span v-if="!capabilities.canWrite" class="readonly">Read-only shared session</span><span class="right"><button v-if="capabilities.canManage && canPause(session)" @click="$emit('pause', session.id)">⏸ Pause</button><button v-if="capabilities.canManage && session.canResume" @click="$emit('resume', session.id)">↻ Resume</button><span class="status">{{ statuses[activeTab] }}</span></span></div><TerminalPane v-show="activeTab === 'agent'" :session="session" :readonly="!capabilities.canWrite" kind="agent" :active="activeTab === 'agent'" @status="statuses.agent = $event" /><TerminalPane v-if="isLive && capabilities.canShell && shellOpened" v-show="activeTab === 'shell'" :session="session" kind="shell" :active="activeTab === 'shell'" @status="statuses.shell = $event" /></div></template>
<style scoped>.term-wrap { flex: 1; display: flex; flex-direction: column; min-width: 0; background: #0E1116; } .term-bar { display: flex; align-items: center; gap: 12px; padding: 8px 14px; border-bottom: 1px solid var(--border); background: var(--panel); } .title { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 13px; } .right { display: flex; gap: 8px; align-items: center; } .tabs { display: flex; gap: 4px; } .tabs button, .back { padding: 4px 10px; font-size: 12px; } .readonly { color: var(--paused); font-size: 12px; } .status { color: var(--muted); font: 12px var(--mono); }</style>
